/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vLOI8N0OZk2
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { PaginationPrevious, PaginationItem, PaginationLink, PaginationNext, PaginationContent, Pagination } from "@/components/ui/pagination"
import ProductCard from "./product-card";
import { ListPagination } from "../list-pagination";

export function ProductList() {
  return (
    (<section className="w-full py-12">
      <div
        className="container grid gap-6 md:gap-8 px-4 md:px-6 max-w-xl mx-auto lg:max-w-none">
        <div
          className="flex flex-col md:flex-row items-start md:items-center gap-4 md:gap-8">
          <div className="grid gap-1">
            <h1 className="text-2xl font-bold tracking-tight">Shop by Sport</h1>
            <p className="text-gray-500 dark:text-gray-400">Find the gear you need for your favorite sport.</p>
          </div>
          <div className="grid gap-4 md:gap-6">
            <form className="grid gap-4 md:gap-6">
              <div className="grid gap-2">
                <Label className="text-base" htmlFor="search">
                  Search
                </Label>
                <Input id="search" placeholder="Search products..." name="search" />
              </div>
            </form>
          </div>
        </div>
        <div className="grid lg:grid-cols-3 gap-8">
          <ProductCard />
          <ProductCard />
        </div>
        <div className="flex justify-center mt-8">
          <ListPagination
            page={1}
            next="?page=2"
            previous="?page=1" 
            onPageChange={() => {}}
            />
        </div>
      </div>
    </section>)
  );
}
