/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/N41qi62DAs7
 */

import { ConversationItem } from "./conversation-item";

export function ConversationList() {
  return (
    <div className="flex flex-col gap-4">
      <ConversationItem />
      <ConversationItem />
      <ConversationItem />
    </div>
  );
}
