"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/N41qi62DAs7
 */

import { useChat } from "@/contexts/chat";
import { ConversationItem } from "./conversation-item";
import { Button } from "../ui/button";
import { useUser } from "@/contexts/user";
import { useEffect } from "react";

export function ConversationList() {
  const user = useUser();
  const chat = useChat();
  const { conversations} = chat;

  useEffect(() => {
    if(user.user){
      chat.getConversations();
    }
  }, [user.user]);

  const startConversation = (e) => {
    e.preventDefault();
    const email = e.target["email"].value;
    chat.createConversation({
      recipients: [email,user.user.email]
    })
  }
  if(!user.user) {
    return (
      <div className="flex flex-col gap-4 min-w-[450px]">
        You have to be logged in to use chat.
      </div>
    )
  }
  return (
    <div className="flex flex-col gap-4 min-w-[450px]">
      <h1 className="text-2xl font-bold tracking-tight">Chat</h1>
      <form className="grid gap-4 md:gap-6" onSubmit={startConversation}>
        <div className="grid gap-2">
          <label className="text-base" htmlFor="email">
            Email of another user
          </label>
          <input
            type="email"
            id="email"
            placeholder="Email of another user"
            name="email"
            className="block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm p-3"
          />
          <Button className="w-full">Start Conversation</Button>
        </div>
      </form>
      <h2 className="text-xl font-bold tracking-tight">Conversations</h2>
      {conversations.map((conversation) => (
        <ConversationItem 
          key={conversation.id} 
          conversation={conversation} 
          user={user.user}
          />
      ))}
    </div>
  );
}
