"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vLOI8N0OZk2
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import RecipieCard from "./recipie-card";
import { ListPagination } from "../list-pagination";
import { useRecipies } from "../../contexts/recipies";
import { useEffect } from "react";

export function RecipieList() {
  const recipies = useRecipies();
  useEffect(() => {
    recipies.getRecipies();
  }, []);

  return (
    (<section className="w-full py-12">
      <div
        className="container grid gap-6 md:gap-8 px-4 md:px-6 max-w-xl mx-auto lg:max-w-none">
        <div
          className="flex flex-col md:flex-row items-start md:items-center gap-4 md:gap-8">
          <div className="grid gap-1">
            <h1 className="text-2xl font-bold tracking-tight">Recipies by Acme</h1>
            <p className="text-gray-500 dark:text-gray-400">
              Find your new favorite dish today!
            </p>
          </div>
          <div className="grid gap-4 md:gap-6">
              <div className="grid gap-2">
                <Label className="text-base" htmlFor="search">
                  Search
                </Label>
                <Input type="search" id="search" placeholder="Search recipies..." name="search" 
                  onKeyDown={(e) => {
                    if(e.key === "Enter") {
                      recipies.getRecipies(e.target.value);
                    }
                  }}
                />
              </div>
          </div>
        </div>
        <div className="grid lg:grid-cols-3 gap-8">
          {recipies.recipies.map((recipie) => (
            <RecipieCard key={recipie.id} recipie={recipie} />
          ))}
        </div>
        {/* <div className="flex justify-center mt-8">
          <ListPagination
            page={1}
            next="?page=2"
            previous="?page=1" 
            onPageChange={() => {}}
            />
        </div> */}
      </div>
    </section>)
  );
}
