"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/e4Ndghg5GHM
*/
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { useRecipies } from "@/contexts/recipies";
import { useUser } from "@/contexts/user";
import Reviews from "./reviews";

export function Recipie() {
  const user = useUser();
  const recipies = useRecipies();
  if(!recipies.recipie) return <div>Loading...</div>;
  return (
    (<div
      className="flex flex-col items-center px-4 py-6 md:px-6 lg:py-16 md:py-12">
      <h1
        className="text-4xl font-bold tracking-tight md:text-5xl lg:leading-[3.5rem]">
        {recipies.recipie.title}     
      </h1>
      <img
        alt="Spaghetti Bolognese"
        className="my-8 object-cover w-full aspect-[3/2] rounded-lg"
        height={400}
        src={recipies.recipie.image}
        width={600} />
      <div className="w-full max-w-2xl">
        <h2 className="text-2xl font-bold tracking-tight md:text-3xl">Ingredients</h2>
        <div className="grid gap-2 mt-4">
          {recipies.recipie.ingredients.map((ingredient) => (

            <div className="flex items-center space-x-2">
            <Checkbox id="ingredient1" />
            <Label htmlFor="ingredient1">
              {ingredient.quantity} {ingredient.unit} {ingredient.name}
            </Label>
          </div>
            ))}
        </div>
        <h2 className="text-2xl font-bold tracking-tight md:text-3xl mt-8">Instructions</h2>
        <ol className="list-decimal list-inside mt-4 space-y-2 text-lg">
          {recipies.recipie.steps.map((step) => (

            <li>
              {step}
          </li>
            ))}
        </ol>
      </div>
      {user.user && user.user._id === recipies.recipie.user && (
      <div className="flex justify-center mt-8">
        <button
          className="bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-lg"
          onClick={() => {
            recipies.deleteRecipie(recipies.recipie._id);
          }}
          type="button">
          Delete
        </button>
      </div>
      )}

      <Reviews />
    </div>)
  );
}
