"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yfNaTOwsq4N
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { useUser } from "../contexts/user";

export function AuthComponent() {
  const user = useUser();

  const onRegister = (e) => {
    e.preventDefault();
    const name = e.target["register-name"].value;
    const email = e.target["register-email"].value;
    const password = e.target["register-password"].value;
    const confirmPassword = e.target["register-confirm-password"].value;
    if (password !== confirmPassword) {
      alert("Passwords do not match");
      return;
    }
    user.onRegister(name, email, password);
  }

  const onLogin = (e) => {
    e.preventDefault();
    const email = e.target["login-email"].value;
    const password = e.target["login-password"].value;
    user.onLogin(email, password);
  }

  return (
    (<div
      className="flex flex-col items-center justify-center min-h-screen min-w-[450px]">
      <div className="w-full max-w-md">
        <div
          className="bg-white dark:bg-gray-800 shadow rounded-lg divide-y divide-gray-200 dark:divide-gray-700">
          <div className="px-5 py-7">
            <h2
              className="text-2xl font-semibold text-center text-gray-700 dark:text-gray-200">Login</h2>
            <form className="space-y-6 mt-7" onSubmit={onLogin}>
              <div>
                <Label htmlFor="login-email">Email</Label>
                <Input id="login-email" placeholder="john@example.com" required type="email" />
              </div>
              <div>
                <Label htmlFor="login-password">Password</Label>
                <Input id="login-password" required type="password" />
              </div>
              <Button className="w-full">Login</Button>
            </form>
          </div>
          <div className="px-5 py-7">
            <h2
              className="text-2xl font-semibold text-center text-gray-700 dark:text-gray-200">Register</h2>
            <form className="space-y-6 mt-7" onSubmit={onRegister}>
              <div>
                <Label htmlFor="register-name">Name</Label>
                <Input id="register-name" placeholder="John Doe" required />
              </div>
              <div>
                <Label htmlFor="register-email">Email</Label>
                <Input id="register-email" placeholder="john@example.com" required type="email" />
              </div>
              <div>
                <Label htmlFor="register-password">Password</Label>
                <Input id="register-password" required type="password" />
              </div>
              <div>
                <Label htmlFor="register-confirm-password">Confirm Password</Label>
                <Input id="register-confirm-password" required type="password" />
              </div>
              <Button className="w-full">Register</Button>
            </form>
          </div>
        </div>
      </div>
    </div>)
  );
}
