/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bX6TPDkRU7F
 */
import { BlogPost } from "./blog-post";

export function BlogList() {
  return (
    (<div className="flex flex-col gap-6 p-4 md:p-6">
      <BlogPost />
      <BlogPost />
      <BlogPost />
    </div>)
  );
}
