"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bX6TPDkRU7F
 */
import { useBlog } from "@/contexts/blog";
import { BlogPost } from "./blog-post";
import { useEffect } from "react";

export function BlogList() {
  const blog = useBlog();

  useEffect(() => {
    blog.getPosts();
  }, []);

  return (
    (<div className="flex flex-col gap-6 p-4 md:p-6">
      {blog.posts.map((post) => (
        <BlogPost key={post.id} post={post} />
      )
      )}
    </div>)
  );
}
